# Generated by Django 5.1.6 on 2025-03-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_media_event_participants_delete_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='event_media'),
        ),
    ]
